root: ./

redirects:
  introduction: README.md
  contract/overview: liquidity-solutions/kyberswap-elastic/developer-guides/README.md
  contract/deployment: liquidity-solutions/kyberswap-elastic/contracts/elastic-contract-addresses.md
  contract/get-pool: liquidity-solutions/kyberswap-elastic/developer-guides/get-elastic-pool-addresses.md
  contract/implement-a-swap: liquidity-solutions/kyberswap-elastic/developer-guides/execute-an-elastic-swap.md
  reference/subgraph-data: liquidity-solutions/kyberswap-elastic/subgraphs.md
  overview/overview-kyberswap-elastic: liquidity-solutions/kyberswap-elastic/README.md
  overview/elastic-walkthrough: liquidity-solutions/kyberswap-elastic/README.md
  overview/anti-JIT-attack: liquidity-solutions/kyberswap-elastic/concepts/anti-sniping-mechanism.md
  overview/motivation: liquidity-solutions/kyberswap-elastic/concepts/README.md
  overview/elastic-pool-apr-calculation: liquidity-solutions/kyberswap-elastic/concepts/apr-calculations.md
  guides/getting-started: liquidity-solutions/kyberswap-elastic/user-guides/README.md
  guides/create-metamask-wallet: kyberswap-solutions/kyberswap-interface/user-guides/connect-your-wallet.md
  guides/connect-metamask-wallet: kyberswap-solutions/kyberswap-interface/user-guides/connect-your-wallet.md
  guides/switch-networks: kyberswap-solutions/kyberswap-interface/user-guides/selecting-preferred-network.md
  guides/swap-tokens-guide: kyberswap-solutions/kyberswap-interface/user-guides/instantly-swap-at-the-best-rates.md
  guides/creating-a-pool: liquidity-solutions/kyberswap-elastic/user-guides/elastic-pool-creation.md
  guides/adding-liquidity: liquidity-solutions/kyberswap-elastic/user-guides/add-liquidity-to-an-existing-elastic-pool.md
  guides/increase-liquidity: liquidity-solutions/kyberswap-elastic/user-guides/increasing-liquidity-on-elastic.md
  guides/collect-fees: liquidity-solutions/kyberswap-elastic/user-guides/elastic-fee-collection.md
  guides/remove-liquidity: liquidity-solutions/kyberswap-elastic/user-guides/removing-liquidity-on-elastic.md
  guides/farming-mechanisms: liquidity-solutions/kyberswap-elastic/concepts/tick-based-farming.md
  guides/how-to-farm: liquidity-solutions/kyberswap-elastic/user-guides/yield-farming-on-elastic.md
  farming-on-elastic/contract-deployment: liquidity-solutions/kyberswap-elastic/contracts/elastic-farming-contract-addresses.md
  kyber-dao/kyber-dao-introduction: governance/kyberdao/README.md
  kyber-dao/staking: governance/kyberdao/user-guides/staking.md
  kyber-dao/voting: governance/kyberdao/user-guides/voting.md
  kyber-dao/others: governance/kyberdao/faq.md
  kyber-dao/fees-to-kyber-dao: governance/kyberdao/fees-to-kyberdao.md
  third-party-integration: reference/third-party-integrations.md
  Classic/introduction: liquidity-solutions/kyberswap-classic/README.md
  Classic/contract/overview: liquidity-solutions/kyberswap-classic/developer-guides/README.md
  Classic/contract/fetching-pool-addresses: liquidity-solutions/kyberswap-classic/developer-guides/get-classic-pool-addresses.md
  Classic/contract/swap-execution: liquidity-solutions/kyberswap-classic/developer-guides/execute-a-classic-swap.md
  Classic/contract/providing-liquidity: liquidity-solutions/kyberswap-classic/developer-guides/providing-liquidity-to-classic-pools.md
  Classic/contract/flash-swaps: liquidity-solutions/kyberswap-classic/developer-guides/flash-swap-on-classic.md
  Classic/contract/contract-addresses: liquidity-solutions/kyberswap-classic/contracts/classic-contract-addresses.md
  Classic/reference/subgraph-data: liquidity-solutions/kyberswap-classic/subgraphs.md
  Classic/overview/how-kyberswap-works: liquidity-solutions/kyberswap-classic/concepts/README.md
  Classic/overview/dynamic-fee: liquidity-solutions/kyberswap-classic/concepts/flexible-fee-adjustment.md
  Classic/overview/kyberswap-ecosystem: README.md
  Classic/overview/adding-liquidity-in-kyberswap: liquidity-solutions/kyberswap-classic/concepts/virtual-balances.md
  Classic/overview/protocol-fee: liquidity-solutions/kyberswap-classic/concepts/protocol-fee.md
  Classic/guides/getting-started: liquidity-solutions/kyberswap-classic/user-guides/README.md
  Classic/guides/create-metamask-wallet: kyberswap-solutions/kyberswap-interface/user-guides/connect-your-wallet.md
  Classic/guides/connect-metamask-wallet: kyberswap-solutions/kyberswap-interface/user-guides/connect-your-wallet.md
  Classic/guides/switch-networks: kyberswap-solutions/kyberswap-interface/user-guides/selecting-preferred-network.md
  Classic/guides/swap-tokens-guide: kyberswap-solutions/kyberswap-interface/user-guides/instantly-swap-at-the-best-rates.md
  Classic/guides/adding-liquidity-guide: liquidity-solutions/kyberswap-classic/user-guides/add-liquidity-to-an-existing-classic-pool.md
  Classic/guides/removing-liquidity-guide: liquidity-solutions/kyberswap-classic/user-guides/removing-liquidity-on-classic.md
  Classic/guides/basic-pool-creation: liquidity-solutions/kyberswap-classic/user-guides/classic-pool-creation.md
  Classic/guides/advanced-pool-creation: liquidity-solutions/kyberswap-classic/user-guides/classic-pool-creation.md
  Classic/guides/yield-farming-guide: liquidity-solutions/kyberswap-classic/user-guides/yield-farming-on-classic.md
  Classic/guides/referral-fee-program: kyberswap-solutions/kyberswap-interface/user-guides/refer-and-get-rewarded.md
  limit-order/getting-started: kyberswap-solutions/limit-order/README.md
  limit-order/signing-data: kyberswap-solutions/limit-order/developer-guides/place-a-limit-order.md
  limit-order/limit-order-api: kyberswap-solutions/limit-order/limit-order-api-specification/README.md
  limit-order/smart-contracts/limit-order-protocol-smart-contract: kyberswap-solutions/limit-order/contracts/limit-order-contract-addresses.md
  limit-order/user-guides/what-is-kyberswap-limit-order: kyberswap-solutions/limit-order/limit-order-api-specification/README.md
  limit-order/user-guides/how-to-create-a-limit-order: kyberswap-solutions/kyberswap-interface/user-guides/trade-at-your-preferred-rates.md
  limit-order/user-guides/how-to-cancel-a-limit-order: kyberswap-solutions/limit-order/user-guides/cancel-limit-orders.md
  limit-order/user-guides/what-are-the-reasons-my-limit-order-doesnt-get-filled: kyberswap-solutions/limit-order/faq.md
  limit-order/user-guides/why-cant-i-view-my-order: kyberswap-solutions/limit-order/faq.md
  limit-order/user-guides/on-which-chains-can-limit-orders-be-executed: kyberswap-solutions/limit-order/faq.md
  limit-order/user-guides/how-do-i-know-if-my-order-has-been-filled-or-not: kyberswap-solutions/limit-order/faq.md
  Aggregator/overview: kyberswap-solutions/kyberswap-aggregator/README.md
  Aggregator/implement-a-swap: kyberswap-solutions/kyberswap-aggregator/developer-guides/execute-a-swap-with-the-aggregator-api.md
  Aggregator/aggregator-api: kyberswap-solutions/kyberswap-aggregator/aggregator-api-specification/evm-swaps.md
  Aggregator/aggregator-solana-api: kyberswap-solutions/kyberswap-aggregator/aggregator-api-specification/solana-swaps.md
  Aggregator/swap-widget/getting-started: kyberswap-solutions/kyberswap-widget/README.md
  Aggregator/swap-widget/example-themes: kyberswap-solutions/kyberswap-widget/README.md
  Aggregator/swap-widget/customize-widget: kyberswap-solutions/kyberswap-widget/developer-guides/customizing-the-kyberswap-widget.md
  kyberswap-solutions/kyberswap-widget/developer-guides/draft-integrating-the-kyberswap-widget: kyberswap-solutions/kyberswap-widget/developer-guides/integrating-the-kyberswap-widget.md
  explanation/appendix: liquidity-solutions/kyberswap-elastic/concepts/README.md
  explanation/core-contracts: liquidity-solutions/kyberswap-elastic/contracts/elastic-core-contracts.md
  explanation/core-libraries: liquidity-solutions/kyberswap-elastic/contracts/elastic-core-libraries.md
  explanation/peripheral-base-contracts: liquidity-solutions/kyberswap-elastic/contracts/elastic-peripheral-base-contracts.md
  explanation/peripheral-library-contracts: liquidity-solutions/kyberswap-elastic/contracts/elastic-peripheral-library-contracts.md
  explanation/periphery-core-contracts: liquidity-solutions/kyberswap-elastic/contracts/elastic-periphery-core-contracts.md
  Legacy/introduction: reference/legacy/getting-started.md
  Legacy/protocol-overview: reference/legacy/protocol/overview.md
  Legacy/smart-contract-architecture: reference/legacy/protocol/smart-contract-architecture.md
  Legacy/trust-security-model: reference/legacy/protocol/trust-and-security-model.md
  Legacy/integrations/getting-started: reference/legacy/integrations/getting-started.md
  Legacy/integrations/use-cases: reference/legacy/integrations/use-cases.md
  Legacy/integrations/integration-types: reference/legacy/integrations/integration-types.md
  Legacy/integrations/smart-contracts: reference/legacy/integrations/smart-contracts.md
  Legacy/integrations/ethers-js: reference/legacy/integrations/ethers-js.md
  Legacy/integrations/restful-api: reference/legacy/integrations/restful-api.md
  Legacy/integrations/slippage-rate-protection: reference/legacy/integrations/slippage-rate-protection.md
  Legacy/integrations/price-feed-security: reference/legacy/integrations/price-feed-security.md
  Legacy/integrations/contract-events: reference/legacy/integrations/contract-events.md
  Legacy/integrations/platform-fees: reference/legacy/integrations/platform-fees.md
  Legacy/reserves/getting-started/overview: reference/legacy/reserves/getting-started/overview.md
  Legacy/reserves/getting-started/why-develop: reference/legacy/reserves/getting-started/why-develop-on-kyber.md
  Legacy/reserves/getting-started/create-new-reserve: reference/legacy/reserves/getting-started/create-new-reserve.md
  Legacy/reserves/getting-started/existing-reserves: reference/legacy/reserves/getting-started/existing-reserves.md
  Legacy/reserves/getting-started/customise-existing-reserves: reference/legacy/reserves/getting-started/customising-existing-reserves.md
  Legacy/reserves/development-guides/fed-price-reserve: reference/legacy/reserves/development-guides/fed-price-reserve.md
  Legacy/reserves/development-guides/automated-price-reserve: reference/legacy/reserves/development-guides/automated-price-reserve.md
  Legacy/reserves/development-guides/reserves-ganache: reference/legacy/reserves/development-guides/reserves-with-ganache.md
  Legacy/reserves/development-guides/orderbook-reserve: reference/legacy/reserves/development-guides/orderbook-reserve.md
  Legacy/reserves/operation/listing-policies: reference/legacy/reserves/operations/listing-policies.md
  Legacy/reserves/operation/reserve-ids: reference/legacy/reserves/operations/reserve-ids.md
  Legacy/reserves/operation/reserves-rebates: reference/legacy/reserves/operations/reserve-rebates.md
  Legacy/reserves/operation/sanity-rates: reference/legacy/reserves/operations/sanity-rates.md
  Legacy/addresses/addresses-intro: reference/legacy/addresses/introduction.md
  Legacy/addresses/addresses-mainnet: reference/legacy/addresses/mainnet.md
  Legacy/addresses/addresses-kovan: reference/legacy/addresses/kovan.md
  Legacy/addresses/addresses-rinkeby: reference/legacy/addresses/rinkeby.md
  Legacy/addresses/addresses-ropsten: reference/legacy/addresses/ropsten.md
  Legacy/api-abi/api_abi-intro: reference/legacy/api-abi/introduction.md
  Legacy/api-abi/getting-started/api_abi-intro: reference/legacy/api-abi/introduction.md
  Legacy/api-abi/restful-api/api_abi-restfulapioverview: reference/legacy/api-abi/restful-api/restful-api-overview.md
  Legacy/api-abi/restful-api/api_abi-restfulapi: reference/legacy/api-abi/restful-api/restful-api.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikybernetworkproxy: reference/legacy/api-abi/core-smart-contracts/ikybernetworkproxy.md
  Legacy/api-abi/core-smart-contracts/api_abi-kybernetworkproxy: reference/legacy/api-abi/core-smart-contracts/kybernetworkproxy.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikybernetwork: reference/legacy/api-abi/core-smart-contracts/ikybernetwork.md
  Legacy/api-abi/core-smart-contracts/api_abi-isimplekyberproxy: reference/legacy/api-abi/core-smart-contracts/isimplekyberproxy.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikybermatchingengine: reference/legacy/api-abi/core-smart-contracts/ikybermatchingengine.md
  Legacy/api-abi/core-smart-contracts/api_abi-kybermatchingengine: reference/legacy/api-abi/core-smart-contracts/kybermatchingengine.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberhint: reference/legacy/api-abi/core-smart-contracts/ikyberhint.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberhinthandler: reference/legacy/api-abi/core-smart-contracts/kyberhinthandler.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberfeehandler: reference/legacy/api-abi/core-smart-contracts/ikyberfeehandler.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberstaking: reference/legacy/api-abi/core-smart-contracts/ikyberstaking.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberstaking: reference/legacy/api-abi/core-smart-contracts/kyberstaking.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberdao: reference/legacy/api-abi/core-smart-contracts/ikyberdao.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberdao: reference/legacy/api-abi/core-smart-contracts/kyberdao.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberstorage: reference/legacy/api-abi/core-smart-contracts/ikyberstorage.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberstorage: reference/legacy/api-abi/core-smart-contracts/kyberstorage.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberhistory: reference/legacy/api-abi/core-smart-contracts/ikyberhistory.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberhistory: reference/legacy/api-abi/core-smart-contracts/kyberhistory.md
  Legacy/api-abi/core-smart-contracts/api_abi-ikyberreserve: reference/legacy/api-abi/core-smart-contracts/ikyberreserve.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberreserve: reference/legacy/api-abi/core-smart-contracts/kyberreserve.md
  Legacy/api-abi/core-smart-contracts/api_abi-conversionrates: reference/legacy/api-abi/core-smart-contracts/conversionrates.md
  Legacy/api-abi/core-smart-contracts/api_abi-liquidityconversionrates: reference/legacy/api-abi/core-smart-contracts/liquidityconversionrates.md
  Legacy/api-abi/core-smart-contracts/api_abi-epochutils: reference/legacy/api-abi/core-smart-contracts/epochutils.md
  Legacy/api-abi/core-smart-contracts/api_abi-iepochutils: reference/legacy/api-abi/core-smart-contracts/iepochutils.md
  Legacy/api-abi/core-smart-contracts/api_abi-kyberfeehandler: reference/legacy/api-abi/core-smart-contracts/kyberfeehandler.md
  Legacy/api-abi/contract-abis/api_abi-abi: reference/legacy/api-abi/contract-abis/abis.md
  Legacy/api-abi/code-snippets/api_abi-tokenquantityconversion: reference/legacy/api-abi/code-snippets/token-quantity-conversion.md
  Legacy/api-abi/misc/api_abi-kybernetwork: reference/legacy/api-abi/misc-contracts/kybernetwork.md
  Legacy/api-abi/misc/api_abi-conversionratesinterface: reference/legacy/api-abi/misc-contracts/conversionratesinterface.md
  Legacy/api-abi/misc/api_abi-permissiongroups: reference/legacy/api-abi/misc-contracts/permissiongroups.md
  Legacy/api-abi/misc/api_abi-sanityrates: reference/legacy/api-abi/misc-contracts/sanityrates.md
  Legacy/api-abi/misc/api_abi-withdrawable: reference/legacy/api-abi/misc-contracts/withdrawable.md
  Legacy/api-abi/misc/api_abi-orderbookreserveinterface: reference/legacy/api-abi/misc-contracts/orderbookreserveinterface.md
  Legacy/api-abi/misc/api_abi-permissionlessorderbookreservelister: reference/legacy/api-abi/misc-contracts/orderbookreservelister.md
  kyberswap-solutions/kyberai/concepts/kyberscore: kyberswap-solutions/kyberai/kyberscore.md
  kyberswap-solutions/kyberswap-interface/user-guides/instantly-swap-at-the-best-rates: kyberswap-solutions/kyberswap-interface/user-guides/instantly-swap-at-superior-rates.md
  liquidity-solutions/kyberswap-elastic/user-guides/yield-farming-on-elastic: liquidity-solutions/kyberswap-elastic/user-guides/yield-farming-on-dynamic-farms.md
  kyberswap-solutions/kyberswap-aggregator/developer-guides/upgrading-from-apiv1-to-apiv2: kyberswap-solutions/kyberswap-aggregator/developer-guides/upgrading-to-apiv1.md
  kyberswap-solutions/kyberswap-widget/widget-iframe: kyberswap-solutions/kyberswap-widget/iframe-alternative.md
  classic/guides/basic-pool-creation: liquidity-solutions/kyberswap-classic/user-guides/classic-pool-creation.md
  getting-started/foundational-topics/decentralized-technologies/draft-dapps: getting-started/foundational-topics/decentralized-technologies/dapps.md
